<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CodeComponents.aspx.cs" Inherits="ComputerShopWebApp.CodeComponents" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindModel" runat="server" Text="Label">Страна</asp:Label><asp:TextBox ID="TextBoxFindModel" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindComponent" runat="server" Text="Найти" OnClick="ButtonFindComponent_Click" />
    <br />        
        <asp:GridView ID="GridViewComponent" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewComponent_RowCancelingEdit" 
            OnRowDeleting="GridViewComponent_RowDeleting" 
            OnRowEditing="GridViewComponent_RowEditing" 
            OnRowUpdating="GridViewComponent_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewComponent_PageIndexChanging"
            Caption="Наименования деталей" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="ComponentId" HeaderText="Код" SortExpression="ComponentId" />
                <asp:TemplateField HeaderText="Тип детали" SortExpression="ComponentTypeId">
                <EditItemTemplate>
                    <asp:DropDownList ID="ComponentTypeIdDropDownList" runat="server" DataSourceID="SqlDataSourceComponentType" DataTextField="ComponentTypeName" DataValueField="ComponentTypeId" SelectedValue='<%# Bind("ComponentTypeId") %>'>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                 <asp:Label ID="ComponentTypeId" runat="server"  Text='<%# Eval("ComponentType.ComponentTypeName") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
                <asp:BoundField DataField="ComponentModel" HeaderText="Модель" SortExpression="Model" />
                <asp:TemplateField HeaderText="Производитель" SortExpression="ManufacturerId">
                <EditItemTemplate>
                    <asp:DropDownList ID="ManufacturerIdDropDownList" runat="server" DataSourceID="SqlDataSourceManufacturer" DataTextField="ManufacturerName" DataValueField="ManufacturerId" SelectedValue='<%# Bind("ComponentManufacturerId") %>'>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                 <asp:Label ID="ManufacturerId" runat="server"  Text='<%# Eval("Manufacturer.ManufacturerName") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
                <asp:TemplateField HeaderText="Страна" SortExpression="CountryId">
                <EditItemTemplate>
                    <asp:DropDownList ID="CountryIdDropDownList" runat="server" DataSourceID="SqlDataSourceCountry" DataTextField="CountryName" DataValueField="CountryId" SelectedValue='<%# Bind("ComponentCountryId") %>'>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                 <asp:Label ID="CountryId" runat="server"  Text='<%# Eval("Country.CountryName") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
                <asp:TemplateField HeaderText="Дата производства" SortExpression="ReleaseDate">
                    <EditItemTemplate>
                        <asp:Calendar ID="ReleaseDateCalendar" runat="server" SelectedDate='<%# Bind("ComponentReleaseDate") %>'></asp:Calendar>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="ReleaseDate" runat="server" Text='<%# Eval("ComponentReleaseDate") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
            <asp:BoundField DataField="ComponentCharacteristics" HeaderText="Характеристики" SortExpression="Characteristics" />
                <asp:BoundField DataField="ComponentWarrantyInMonths" HeaderText="Гарантия(м)" SortExpression="WarrantyPeriodInMonth" />
                <asp:BoundField DataField="ComponentDescription" HeaderText="Описание" SortExpression="Description" />
                <asp:BoundField DataField="ComponentPrice" HeaderText="Цена" SortExpression="Price" />
            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить новую деталь:</strong>
            <br />
            Тип детали
           <asp:DropDownList ID="ComponentTypeDropDownList" DataSourceID="SqlDataSourceComponentType" DataValueField="ComponentTypeId" DataTextField="ComponentTypeName" runat="server"></asp:DropDownList>
            <br />
            <asp:label runat="server">Наименование модели:</asp:label><asp:TextBox ID="TextBoxModel" runat="server"></asp:TextBox>
            Производитель
           <asp:DropDownList ID="ManufacturerDropDownList" DataSourceID="SqlDataSourceManufacturer" DataValueField="ManufacturerId" DataTextField="ManufacturerName" runat="server"></asp:DropDownList>
            Страна
           <asp:DropDownList ID="CountryDropDownList" DataSourceID="SqlDataSourceCountry" DataValueField="CountryId" DataTextField="CountryName" runat="server"></asp:DropDownList>
            <br />
            <asp:label runat="server">Год производства:</asp:label><asp:Calendar ID="TextBoxReleaseDate" runat="server"></asp:Calendar>
            <br />
            <asp:label runat="server">Характеристики:</asp:label><asp:TextBox ID="TextBoxCharacteristic" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Гарантия(м):</asp:label><asp:TextBox ID="TextBoxWarranty" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Описание:</asp:label><asp:TextBox ID="TextBoxDescription" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Цена:</asp:label><asp:TextBox ID="TextBoxPrice" runat="server"></asp:TextBox>
            <br />
        </td>
        <td>
            <asp:Button ID="ButtonAddComponent" runat="server" Text="Добавить" OnClick="ButtonAddComponent_Click" />

        </td>
</tr>
</table>
    <asp:SqlDataSource ID="SqlDataSourceComponentType" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ComputerShopConnectionString %>" 
        SelectCommand="SELECT [ComponentTypeId], [ComponentTypeName] FROM [ComponentTypes]">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceManufacturer" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ComputerShopConnectionString %>" 
        SelectCommand="SELECT [ManufacturerId], [ManufacturerName] FROM [Manufacturers]">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceCountry" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ComputerShopConnectionString %>" 
        SelectCommand="SELECT [CountryId], [CountryName] FROM [Countries]">
    </asp:SqlDataSource>
    </asp:Content>
