<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CodeManufacturers.aspx.cs" Inherits="ComputerShopWebApp.CodeManufacturers" %>

    <asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
            <br />
    <table border="0">
        <tr>
        <td>
        <asp:Label ID="LabelFindManufacturer" runat="server" Text="Label">Производитель</asp:Label><asp:TextBox ID="TextBoxFindManufacturer" runat="server"></asp:TextBox>
            <asp:Button ID="ButtonFindManufacturer" runat="server" Text="Найти" OnClick="ButtonFindManufacturer_Click" />
        <br />        
            <asp:GridView ID="GridViewManufacturer" runat="server" AutoGenerateColumns="False"
                AllowPaging="True" 
                AutoGenerateDeleteButton="True" 
                AutoGenerateEditButton="True" 
                OnRowCancelingEdit="GridViewManufacturer_RowCancelingEdit" 
                OnRowDeleting="GridViewManufacturer_RowDeleting" 
                OnRowEditing="GridViewManufacturer_RowEditing" 
                OnRowUpdating="GridViewManufacturer_RowUpdating" PageSize="15" 
                OnPageIndexChanging="GridViewManufacturer_PageIndexChanging"
                Caption="Наименования производителей" 
                EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
                <Columns>
                    <asp:BoundField DataField="ManufacturerId" HeaderText="Код" SortExpression="ManufacturerId" />
                    <asp:BoundField DataField="ManufacturerName" HeaderText="Название" SortExpression="ManufacturerName" />
                </Columns>
            
        </asp:GridView>
            </td>
            <td>
            <strong>Добавить нового производителя:</strong>
                <br />
                <asp:label runat="server">Наименование производителя:</asp:label><asp:TextBox ID="TextBoxManufacturerName" runat="server"></asp:TextBox>
                <br />
            </td>
            <td>
                <asp:Button ID="ButtonAddManufacturer" runat="server" Text="Добавить" OnClick="ButtonAddManufacturer_Click" />

            </td>
    </tr>
    </table>
        </asp:Content>
