<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CodeCountries.aspx.cs" Inherits="ComputerShopWebApp.CodeCountries" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindCountry" runat="server" Text="Label">Страна</asp:Label><asp:TextBox ID="TextBoxFindCountry" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindCountry" runat="server" Text="Найти" OnClick="ButtonFindCountry_Click" />
    <br />        
        <asp:GridView ID="GridViewCountry" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewCountry_RowCancelingEdit" 
            OnRowDeleting="GridViewCountry_RowDeleting" 
            OnRowEditing="GridViewCountry_RowEditing" 
            OnRowUpdating="GridViewCountry_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewCountry_PageIndexChanging"
            Caption="Наименования производителей" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="CountryId" HeaderText="Код" SortExpression="CountryId" />
                <asp:BoundField DataField="CountryName" HeaderText="Название" SortExpression="CountryName" />
            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить новую страну:</strong>
            <br />
            <asp:label runat="server">Наименование страны:</asp:label><asp:TextBox ID="TextBoxCountryName" runat="server"></asp:TextBox>
            <br />
        </td>
        <td>
            <asp:Button ID="ButtonAddCountry" runat="server" Text="Добавить" OnClick="ButtonAddCountry_Click" />

        </td>
</tr>
</table>
    </asp:Content>

