# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1095, 864)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Загрузки/delicious_logo_icon_124323.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QVBoxLayout()
        self.menu.setSpacing(6)
        self.menu.setObjectName("menu")
        self.task1_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task1_button.sizePolicy().hasHeightForWidth())
        self.task1_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task1_button.setFont(font)
        self.task1_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.task1_button.setObjectName("task1_button")
        self.menu.addWidget(self.task1_button)
        self.task2_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task2_button.sizePolicy().hasHeightForWidth())
        self.task2_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task2_button.setFont(font)
        self.task2_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.task2_button.setObjectName("task2_button")
        self.menu.addWidget(self.task2_button)
        self.task3_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task3_button.sizePolicy().hasHeightForWidth())
        self.task3_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task3_button.setFont(font)
        self.task3_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.task3_button.setObjectName("task3_button")
        self.menu.addWidget(self.task3_button)
        self.task4_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task4_button.sizePolicy().hasHeightForWidth())
        self.task4_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task4_button.setFont(font)
        self.task4_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.task4_button.setObjectName("task4_button")
        self.menu.addWidget(self.task4_button)
        self.task5_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task5_button.sizePolicy().hasHeightForWidth())
        self.task5_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task5_button.setFont(font)
        self.task5_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.task5_button.setObjectName("task5_button")
        self.menu.addWidget(self.task5_button)
        self.task6_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task6_button.sizePolicy().hasHeightForWidth())
        self.task6_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task6_button.setFont(font)
        self.task6_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.task6_button.setObjectName("task6_button")
        self.menu.addWidget(self.task6_button)
        self.task7_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task7_button.sizePolicy().hasHeightForWidth())
        self.task7_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task7_button.setFont(font)
        self.task7_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.task7_button.setObjectName("task7_button")
        self.menu.addWidget(self.task7_button)
        self.task8_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task8_button.sizePolicy().hasHeightForWidth())
        self.task8_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task8_button.setFont(font)
        self.task8_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.task8_button.setObjectName("task8_button")
        self.menu.addWidget(self.task8_button)
        self.task9_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task9_button.sizePolicy().hasHeightForWidth())
        self.task9_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task9_button.setFont(font)
        self.task9_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.task9_button.setObjectName("task9_button")
        self.menu.addWidget(self.task9_button)
        self.task10_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task10_button.sizePolicy().hasHeightForWidth())
        self.task10_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.task10_button.setFont(font)
        self.task10_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.task10_button.setObjectName("task10_button")
        self.menu.addWidget(self.task10_button)
        self.horizontalLayout.addLayout(self.menu)
        self.user_interface = QtWidgets.QVBoxLayout()
        self.user_interface.setObjectName("user_interface")
        self.tasks = QtWidgets.QVBoxLayout()
        self.tasks.setObjectName("tasks")
        self.tasks_data_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tasks_data_label.setFont(font)
        self.tasks_data_label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tasks_data_label.setObjectName("tasks_data_label")
        self.tasks.addWidget(self.tasks_data_label)
        self.tasks_data_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tasks_data_text.sizePolicy().hasHeightForWidth())
        self.tasks_data_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.tasks_data_text.setFont(font)
        self.tasks_data_text.setReadOnly(True)
        self.tasks_data_text.setObjectName("tasks_data_text")
        self.tasks.addWidget(self.tasks_data_text)
        self.user_interface.addLayout(self.tasks)
        self.solve_field = QtWidgets.QVBoxLayout()
        self.solve_field.setObjectName("solve_field")
        self.inout = QtWidgets.QHBoxLayout()
        self.inout.setObjectName("inout")
        self.input = QtWidgets.QVBoxLayout()
        self.input.setObjectName("input")
        self.input_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.input_label.setFont(font)
        self.input_label.setObjectName("input_label")
        self.input.addWidget(self.input_label)
        self.input_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_text.setFont(font)
        self.input_text.setObjectName("input_text")
        self.input.addWidget(self.input_text)
        self.inout.addLayout(self.input)
        self.output = QtWidgets.QVBoxLayout()
        self.output.setObjectName("output")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_label.setFont(font)
        self.output_label.setObjectName("output_label")
        self.output.addWidget(self.output_label)
        self.output_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_text.setFont(font)
        self.output_text.setReadOnly(True)
        self.output_text.setObjectName("output_text")
        self.output.addWidget(self.output_text)
        self.inout.addLayout(self.output)
        self.solve_field.addLayout(self.inout)
        self.solve_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solve_button.sizePolicy().hasHeightForWidth())
        self.solve_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.solve_button.setFont(font)
        self.solve_button.setObjectName("solve_button")
        self.solve_field.addWidget(self.solve_button)
        self.user_interface.addLayout(self.solve_field)
        self.horizontalLayout.addLayout(self.user_interface)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Олимпиадные задачи"))
        self.task1_button.setText(_translate("MainWindow", "Задание №1"))
        self.task2_button.setText(_translate("MainWindow", "Задание №2"))
        self.task3_button.setText(_translate("MainWindow", "Задание №3"))
        self.task4_button.setText(_translate("MainWindow", "Задание №4"))
        self.task5_button.setText(_translate("MainWindow", "Задание №5"))
        self.task6_button.setText(_translate("MainWindow", "Задание №6"))
        self.task7_button.setText(_translate("MainWindow", "Задание №7"))
        self.task8_button.setText(_translate("MainWindow", "Задание №8"))
        self.task9_button.setText(_translate("MainWindow", "Задание №9"))
        self.task10_button.setText(_translate("MainWindow", "Задание №10"))
        self.tasks_data_label.setText(_translate("MainWindow", "Обозреватель заданий"))
        self.input_label.setText(_translate("MainWindow", "Поле ввода"))
        self.output_label.setText(_translate("MainWindow", "Поле вывода"))
        self.solve_button.setText(_translate("MainWindow", "Решить задачу"))
